replay-tests: add an empty page for upcoming tag tests
Add an empty page for the helloworld test application for upcoming tag
tests.
Exclude it from uitest-netty4 task, because it casues the very same
TimeoutException (TagsSpec.java was the original file name):

org.openqa.selenium.TimeoutException: Navigation timed out after 30000 ms
Build info: version: '4.28.0', revision: 'ac342546e9'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-52-generic', java.version: '17.0.14'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [62048eeb-6de6-4e1f-a09f-4538f68b9165, get {url=http://localhost:35077/empty}]
selenide.url: http://localhost:35077/empty
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 135.0, moz:accessibilityChecks: false, moz:buildID: 20250130195129, moz:debuggerAddress: 127.0.0.1:26674, moz:geckodriverVersion: 0.35.0, moz:headless: false, moz:platformVersion: 6.8.0-52-generic, moz:processID: 44707, moz:profile: /tmp/rust_mozprofileEQ9uft, moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://127.0.0.1:26674/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, userAgent: Mozilla/5.0 (X11; Linux x86...}
selenide.baseUrl: http://localhost:35077
Session ID: 62048eeb-6de6-4e1f-a09f-4538f68b9165
	at java.base@17.0.14/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.14/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.14/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.14/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base@17.0.14/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at app//org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at app//org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at app//org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at app//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
	at app//org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at app//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at app//org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:313)
	at app//org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:1090)
	at app//com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:69)
	at app//com.codeborne.selenide.logevents.SelenideLogger.lambda$run$0(SelenideLogger.java:99)
	at app//com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:128)
	at app//com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:98)
	at app//com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:65)
	at app//com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:29)
	at app//com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:86)
	at app//com.codeborne.selenide.Selenide.open(Selenide.java:50)
	at app//ui.hello.TagsSpec.openEmptyPage(TagsSpec.java:11)
	...