replay-tests: add failing tests for @include with /conf prefix
The referenced configuration files are both on local file system and on
classpath.

20:48:18,288 WARN  [play.PropertiesConfLoader] ~ Missing include: @include.core
java.lang.NullPointerException: File not found in classpath: application.core.conf
	at java.base/java.util.Objects.requireNonNull(Objects.java:336)
	at play.ClasspathResource.<init>(ClasspathResource.java:42)
	at play.ClasspathResource.file(ClasspathResource.java:26)
	at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:52)
	at play.PropertiesConfLoader.resolveIncludes(PropertiesConfLoader.java:143)
	at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:71)
	at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:47)
	at play.PropertiesConfLoader.readConfiguration(PropertiesConfLoader.java:43)
	at play.Play.readConfiguration(Play.java:221)
	at play.Play.start(Play.java:237)
	at hello.HelloWorldApp.start(HelloWorldApp.java:18)
	at hello.HelloWorldApp.main(HelloWorldApp.java:22)
20:48:18,288 WARN  [play.PropertiesConfLoader] ~ Missing include: @include.app
java.lang.NullPointerException: File not found in classpath: application.app.conf
	at java.base/java.util.Objects.requireNonNull(Objects.java:336)
	at play.ClasspathResource.<init>(ClasspathResource.java:42)
	at play.ClasspathResource.file(ClasspathResource.java:26)
	at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:52)
	at play.PropertiesConfLoader.resolveIncludes(PropertiesConfLoader.java:143)
	at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:71)
	at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:47)
	at play.PropertiesConfLoader.readConfiguration(PropertiesConfLoader.java:43)
	at play.Play.readConfiguration(Play.java:221)
	at play.Play.start(Play.java:237)
	at hello.HelloWorldApp.start(HelloWorldApp.java:18)
	at hello.HelloWorldApp.main(HelloWorldApp.java:22)