replay-tests: add failing example with '@' for resources on classpath
Tag '@{...}' is for reverse routing, see documentation:
https://www.playframework.com/documentation/1.5.x/templates#Actionsor

Calling '@{...}' with a resource on a classpath fails with
play.exceptions.NoRouteFoundException:

09:54:56,765 ERROR [play.server.javanet.PlayHandler] ~ Internal Server Error (500) for GET / (GTAppClassException)
play.template2.exceptions.GTAppClassException: No route found to display file /public/images/favicon.png (file not found)
	at play.mvc.Router.reverseWithCheck(Router.java:306)
	at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.__reverseWithCheck(GTJavaBase1xImpl.java:42)
	at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.__reverseWithCheck_absolute_false(GTJavaBase1xImpl.java:38)
	at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:146)
	at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:110)
	at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:96)
	at play.template2.compile.GTInternalFastTags.tag_include(GTInternalFastTags.java:127)
	at /my_tmpdir_in_the_workdir/classpathtemplates/hello.html.(line:5)
	at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:146)
	at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:110)
	at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:96)
	at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:104)
	at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:67)
	at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:54)
	at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:38)
	at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:73)
	at play.rebel.View.renderView(View.java:71)
	at play.rebel.View.apply(View.java:50)
	at play.mvc.ActionInvoker.applyResult(ActionInvoker.java:191)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:158)
	at play.server.javanet.PlayHandler$JavaNetInvocation.execute(PlayHandler.java:434)
	at play.server.javanet.PlayHandler$JavaNetInvocation.lambda$run$0(PlayHandler.java:409)
	at play.db.jpa.JPA.withTransaction(JPA.java:271)
	at play.db.jpa.JPA.withinFilter(JPA.java:172)
	at play.server.javanet.PlayHandler$JavaNetInvocation.run(PlayHandler.java:407)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: play.template2.exceptions.GTAppClassException: No route found to display file /public/images/favicon.png (file not found)
	... 31 more
Caused by: play.exceptions.NoRouteFoundException: No route found to display file /public/images/favicon.png (file not found)
	... 31 more