fix ClassCastException in RequestLogPlugin
The issue was caused by accidentally importing `java.lang.Error` instead of `play.mvc.results.Error` :)

```
java.lang.ClassCastException: class java.lang.Error cannot be cast to class play.mvc.results.Result (java.lang.Error is in module java.base of loader 'bootstrap'; play.mvc.results.Result is in unnamed module of loader 'app')
	at play.modules.logger.RequestLogPlugin.onActionInvocationFinally(RequestLogPlugin.java:107)
```