replay-tests: add failing test for using "conf/" directory
Modify "multi-module-app" test to use the "conf/" directory:
- conf/application.conf
- conf/routes

To achieve this let move the "conf/" directory (which location is
defined in replay-tests.gradle) to the default resources location:
"src/main/resources/".

With this change these files would be at classpath
"conf/application.conf" and "conf/routes", causing NullPointerException

HelloWorldSpec > openHelloWorldPage() FAILED
    java.lang.NullPointerException: File not found in classpath: application.conf
        at java.base/java.util.Objects.requireNonNull(Objects.java:336)
        at play.ClasspathResource.<init>(ClasspathResource.java:42)
        at play.ClasspathResource.file(ClasspathResource.java:26)
        at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:34)
        at play.PropertiesConfLoader.readOneConfigurationFile(PropertiesConfLoader.java:30)
        at play.PropertiesConfLoader.readConfiguration(PropertiesConfLoader.java:26)
        at play.Play.readConfiguration(Play.java:230)
        at play.Play.init(Play.java:138)
        at play.server.Starter.start(Starter.java:19)
        at hello.HelloWorldApp.start(HelloWorldApp.java:7)
        at ui.hello.BaseSpec.startApp(BaseSpec.java:23)
        at ui.hello.BaseSpec.setUp(BaseSpec.java:17)

Ref: #198