replay-tests: exercise tags/stylesheet.tag as it's currently failing
Play.getVirtualFile() was renamed to Play.file() in commit
397f4cac915af7be84753d009b6bcc84cb3c0d5e and we got
groovy.lang.MissingMethodException now:

groovy.lang.MissingMethodException: No signature of method: static play.Play.getVirtualFile() is applicable for argument types: (String) values: [app/public/stylesheets/empty.css]
	at tags/stylesheet.tag.(line:18)

16:41:42,133 ERROR [play.server.javanet.PlayHandler] ~ Internal Server Error (500) for GET /empty (GTAppClassException)
play.template2.exceptions.GTAppClassException: File not found: app/public/stylesheets/empty.css
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at tags/stylesheet.tag.(line:20)
	at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:146)
	at play.template2.GTJavaBase.invokeTagFile(GTJavaBase.java:290)
	at /app/views/HelloWorld/empty.html.(line:4)
	at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:146)
	at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:110)
	at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:96)
	at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:104)
	at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:67)
	at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:54)
	at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:38)
	at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:73)
	at play.rebel.View.renderView(View.java:71)
	at play.rebel.View.apply(View.java:50)
	at play.mvc.ActionInvoker.applyResult(ActionInvoker.java:191)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:158)
	at play.server.javanet.PlayHandler$JavaNetInvocation.execute(PlayHandler.java:434)
	at play.server.javanet.PlayHandler$JavaNetInvocation.lambda$run$0(PlayHandler.java:409)
	at play.db.jpa.JPA.withTransaction(JPA.java:271)
	at play.db.jpa.JPA.withinFilter(JPA.java:172)
	at play.server.javanet.PlayHandler$JavaNetInvocation.run(PlayHandler.java:407)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: play.template2.exceptions.GTAppClassException: File not found: app/public/stylesheets/empty.css
	... 30 more
Caused by: play.exceptions.TagInternalException: File not found: app/public/stylesheets/empty.css
	... 30 more
Caused by: groovy.lang.MissingMethodException: No signature of method: static play.Play.getVirtualFile() is applicable for argument types: (String) values: [app/public/stylesheets/empty.css]
	at tags/stylesheet.tag.(line:18)
	... 26 more